name: Run Tests By Service 

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'service to test'
        required: true
        default: 'service1'
        type: choice
        options:
          - 'service1'
          - 'service2'
          - 'service3'

env:
  SERVICES_TEST_CONFIG: |
    {
      "service1": "./tests/service1",
      "service2": "./tests/service2",
      "service3": "./tests/service3"
    }

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      test_folder: ${{ steps.set-test-folder.outputs.test_folder }}
    steps:
      - id: set-test-folder
        run: |
          input_service="${{ inputs.service }}"
          echo "input_service: $input_service"
          value=$(echo "${SERVICES_TEST_CONFIG}" | jq -r --arg input_service "$input_service" '.[$input_service]')
          echo "test_folder:[$value]"
          echo "test_folder=$value" >> $GITHUB_OUTPUT
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests in ${{ needs.job1.outputs.test_folder }}"
